on:
  push:
  pull_request:
  schedule:
    - cron: '11 15 * * *'
permissions: { }
jobs:
  toolchain:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - 'macos-15'
          - 'macos-15-intel'
    runs-on: ${{ matrix.runner }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SCCACHE_REGION: us-west-2
      SCCACHE_BUCKET: toolchain-tools-sccache
    steps:
      - uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - name: Build LLVM Toolchain
        run: |
          cd toolchain-bootstrap
          just llvm-apple-native

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: toolchain-${{ matrix.runner }}
          path: toolchain-bootstrap/build/llvm-*-apple-darwin.tar.zst
